language: python
python:
- 2.7
env:
  global:
    - export BOTO_CONFIG=/dev/null
install:
- pip install -e .[tests]
- pip install coveralls
script:
- py.test tests/ --cov=confu --cov-report term-missing
after_success:
- coveralls
deploy:
  provider: pypi
  user: somepie
  password:
    secure: a0cG8ejM2147aUqBKwg7UpJKdgmZiXY4Qx/B1VplrlMf01BmJcAJACREZDF93/Ko6uiOaaGCJwhiPV/tGfrTAYuqfijM7gGGILGgWOtJIm9biHX5aGEqkGHHR57gQTYpXOXTqPTqvu9ZQbgn3L0EX0Dy5KOQwGig3oh606MxtI8=
  on:
    all_branches: true
    tags: true
